### ISSUE TITLE
thebe  button not work

### ISSUE THREAD

**Issue by liuhuanshuo** [QuantEcon/lecture-python-programming#170]
This is a good theme, is there a way to add a thebe button in the place below so that the code can be executed on the page
![](https://liuzaoqi.oss-cn-beijing.aliyuncs.com/picgo/202111251850896.png)

I tried setting `thebe:true`, but it didn't work
![](https://liuzaoqi.oss-cn-beijing.aliyuncs.com/picgo/202111252056963.png)

**Comment by mmcky** [comment]
thanks @liuhuanshuo -- currently `thebe` is not supported directly but we do have the lecture notebook running directly on binder which can be accessed via the "play" button. 

![Screen Shot 2021-11-26 at 1 52 23 pm](https://user-images.githubusercontent.com/8263752/143519710-64ffc749-d445-4b5d-a0bc-456f8d15d20a.png)

We will look at adding `thebe` in the future for in place execution but this is how we support execution on the project at the time being.

**Comment by liuhuanshuo** [comment]
> thanks @liuhuanshuo -- currently `thebe` is not supported directly but we do have the lecture notebook running directly on binder which can be accessed via the "play" button.
> 
> ![Screen Shot 2021-11-26 at 1 52 23 pm](https://user-images.githubusercontent.com/8263752/143519710-64ffc749-d445-4b5d-a0bc-456f8d15d20a.png)
> 
> We will look at adding `thebe` in the future for in place execution but this is how we support execution on the project at the time being.

Thanks for your reply

I really like your theme and am going to use it for my project

I know that thebe is not supported in the current version and I would like to develop this feature

I could try adding a thebe button to Topbar by modifying `layout.html` in the source code, but that doesn't seem to work

Can you give me some ideas on how to modify it? I would love to contribute to this library!

**Comment by mmcky** [comment]
Right - I see @liuhuanshuo. thanks for the kind words re: theme.

The theme is defined by:

https://github.com/quantecon/quantecon-book-theme

so that is where support for `thebe` would need to be added and then use `_config.yml` to activate the option. Perhaps we can open a feature request on the `quantecon-book-theme`. We have been looking to find some time to make that theme more useable by others by adding some further config options to control logos etc. Perhaps we can work with you on that aspect (cc: @AakashGfude)
