### ISSUE TITLE
Feature jupyterlab?

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-python-programming#190]
Should we discuss or use Jupyterlab in https://python-programming.quantecon.org/getting_started.html ?

@mmcky @shlff , what is your sense of progress of Jupyterlab?  Is it becoming dominant or fading?

@HumphreyYang is tring to determine whether we should feature it.

**Comment by mmcky** [comment]
hey @jstac when @HumphreyYang and I met the other day -- my 2c that I shared with @HumphreyYang was:

We should only really invest in jupyterlab if there is a feature that would make the lectures better (i.e. integrated graphs, dashboards etc.). I get the sense that `jupyter notebook` is going to be supported for a long time due to its simplicity and ability to focus on a single notebook. The notebook format is also shared by both platforms. 

To my knowledge the key difference is in how extensions are written (i.e. they are written for jupyterlab or jupyter notebook) so if the javascript side of `mystjs` develops a jupyter lab extension -- well worth the transition (as we can remove the need to maintain sphinx-tojupyter etc.). The other difference is the interface. 

The "live" services we offer such as Google Colab is also notebook centric (Rather than a lab view). 

What I suggest is we have a small section on `jupyterlab` perhaps and let students be aware of both options. But I don't think we need to update all the embedded figures and images to jupyterlab as you get less real estate on-screen to show content.

This might all be biased based on my current workflows, but that is my thinking.

**Comment by jstac** [comment]
> What I suggest is we have a small section on jupyterlab perhaps and let students be aware of both options. But I don't think we need to update all the embedded figures and images to jupyterlab as you get less real estate on-screen to show content.

I agree @mmcky .  In fact I think https://python-programming.quantecon.org/getting_started.html#option-1-jupyterlab is sufficient, unless someone wants to add a few more lines to that section (CC @HumphreyYang )

**Comment by HumphreyYang** [comment]
Thank you so much for your input @jstac and @mmcky, I will close this issue as not planned. I will keep these in mind when I look into Chapter 2 to see if there is anything I can add below that section.
